### ISSUE TITLE
formating issues in book

### ISSUE THREAD

**Issue by johngrabner** [PacktPublishing/Neural-Networks-with-Keras-Cookbook#1]
I have purchased many books and video's on machine learning, and your book is the best so far.
However, the amazon kindle version has a bunch of formatting issues.
![formatting issues](https://user-images.githubusercontent.com/8209285/73371554-76d06180-427b-11ea-8e9d-5c82ee873aab.png)

**Comment by shubham763** [comment]
Hi @johngrabner 
It is updated now.
